### ISSUE TITLE
Hi~ Why don't add a BackToTop button?

### ISSUE THREAD

**Issue by ghost** [jonsuh/jonsuh.com#3]
Hello buddy,
I really appreciate you for sharing this nice jekyll theme.
I'm an android developer without any web skill. I've made a blog use jekyll too but have **some issue**.

Function description:
Need 1: 
I want the footer always stay in bottom even the body is empty.(I can solve it through this [code](http://codepen.io/cbracco/pen/zekgx))
Need 2:
I want add BackToTop button. (I have realized this [function](http://www.johnwatsondev.com/Say-Hello-To-Everybody/))

Here is the **KEY** problem. I cannot realize two function **together**. lol
When i accoplished **need1** but **need2** is broken. Vise versa!

Could you give me some useful advise?
Best regard~

**Comment by ghost** [comment]
My blog [Home Page](http://www.johnwatsondev.com/)  just realized **Need2**. 
Look forward for your reply. :)

**Comment by jonsuh** [comment]
Hi John—feel free to contact me via email from my site. Closing this issue since it doesn't pertain to my site.

**Comment by ghost** [comment]
Sorry，it's my fault.
Thx vm for response anyway.
I'v solved it. :)
